import { Geist, Geist_Mono, Anton, Manrope } from "next/font/google";
import Header from "@components/Header/Header";
import Footer from "@components/Footer/Footer";
import styles from './layout.module.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

config.autoAddCss = false;   

import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const anton = Anton({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-anton',
  weight: ['400'],
});

const manrope = Manrope({
    weight: ['400'],
  variable: "--font-manrope",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr"
      suppressHydrationWarning="true"
      data-lt-installed="true"
    >
      <body className={`${geistSans.variable} ${manrope.variable} ${geistMono.variable} ${anton.variable} ${styles.body}`}>
        <header>
          <Header />
        </header>
        <main className={styles.main}>
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
